export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const ADD5 = "ADD5"
export const SUB5 = "SUB5"
export const MAKE_RESULT = "MAKE_RESULT"
export const DELETE_RESULT = "DELETE_RESULT"